apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proxysql
      protocol: TCP
      name: proxysql
  selector:
    {{- include "proxysql.selectorLabels" . | nindent 4 }}
