{{- $replicas := .Values.replicaCount | int -}}
{{- $fullname := include "proxysql.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql.fullname" . }}-config
data: 
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables=
    {
      admin_credentials="admin:admin;radmin:radmin"
      mysql_ifaces="0.0.0.0:6032"
      cluster_username="radmin"
      cluster_password="radmin"
      cluster_check_interval_ms=200
      cluster_check_status_frequency=100
      cluster_mysql_query_rules_save_to_disk=true
      cluster_mysql_servers_save_to_disk=true
      cluster_mysql_users_save_to_disk=true
      cluster_proxysql_servers_save_to_disk=true
      cluster_mysql_query_rules_diffs_before_sync=3
      cluster_mysql_servers_diffs_before_sync=3
      cluster_mysql_users_diffs_before_sync=3
      cluster_proxysql_servers_diffs_before_sync=3
    }

    mysql_variables=
    {
      threads=2
      max_connections=2048
      default_query_delay=0
      default_query_timeout=36000000
      have_compress=true
      poll_timeout=2000
      interfaces="0.0.0.0:6033"
      default_schema="information_schema"
      stacksize=1048576
      server_version="8.0.20"
      connect_timeout_server=3000
      monitor_username="monitor"
      monitor_password="monitor"
      monitor_history=600000
      monitor_connect_interval=5000
      monitor_ping_interval=2000
      monitor_read_only_interval=1500
      monitor_read_only_timeout=500
      ping_interval_server_msec=15000
      ping_timeout_server=500
      commands_stats=true
      sessions_sort=true
      connect_retries_on_failure=10
    }

    # defines all the MySQL users
    mysql_users:
    (
      { username = "root" , password = "XHCO2ydDXj" , default_hostgroup = 0 , active = 1 },
      { username = "monitor" , password = "monitor" , default_hostgroup = 0 , active = 1 }
    )



    #defines MySQL Query Rules
    mysql_query_rules:
    (
      {
        rule_id=1
        active=1
        match_pattern="^SELECT .* FOR UPDATE$"
        destination_hostgroup=0
        apply=1
      },
      {
        rule_id=2
        active=1
        match_pattern="^SELECT"
        destination_hostgroup=1
        apply=1
      }
    )

    scheduler=
    (
      {
        id=1
        active=1
        interval_ms=5000
        filename="/bin/bash"
        arg1="/usr/local/sbin/config-watcher.sh"
        arg2=""
        arg3=""
        arg4=""
        arg5=""
      }
    )


    mysql_replication_hostgroups=
    (
            {
                    writer_hostgroup=0
                    reader_hostgroup=1
                    comment="RHG1"
          }
    )


  liveness.sh: |
    #!/bin/bash
    set -e

    # this needs to be smarter. It should be able to tell if the container is running
    # and accepting traffic
    exit 0

  readiness.sh: |
    #!/bin/bash
    set -e

    mbin="/usr/bin/mysql"
    lcon="-h127.0.0.1 -P6032 -uadmin -padmin"
    opts="-NB"

    proxysql_peers_available=$($mbin $lcon $opts -e"select count(*) from runtime_proxysql_servers")
  
    if [[ $proxysql_peers_available -eq {{ $replicas }} ]];
    then
      echo "ProxySQL peers configured"
      exit 0
    else
      echo "ProxySQL peers not yet configured or failed"
      exit 1
    fi

  drain.sh: |
    #!/bin/bash
    CONNECTIONS=$(mysqladmin processlist -P6032 -h127.0.0.1 -uadmin -padmin | grep [0-9] -c)
    echo "${CONNECTIONS}"

    while [[ ${CONNECTIONS} -gt 0 ]]; do
      sleep 5
      CONNECTIONS=$(mysqladmin processlist -P6032 -h127.0.0.1 -uadmin -padmin | grep [0-9] -c)
      echo "${CONNECTIONS}"
    
    done

    exit 0

  config-watcher.sh: |
    #!/bin/bash
    CUR_CS=$(/usr/bin/md5sum $0 | /usr/bin/awk '{print $1}')
    PRE_CS=$(/bin/cat /tmp/cs.file | /usr/bin/awk '{print $1}')

    if [[ $CUR_CS != $PRE_CS ]];
    then
      /bin/echo "Diffs detected, executing"
      /usr/bin/mysql -uadmin -padmin -h127.0.0.1 -P6032 -e"
        
        DELETE FROM proxysql_servers;

        {{ range $i, $e := until $replicas}}
        INSERT INTO proxysql_servers (hostname,port,weight,comment) 
          VALUES ('{{ $fullname }}-{{ $e }}.{{ $fullname }}-headless',6032,{{ $e }},'{{ $fullname }}-{{ $e }}.{{ $fullname }}-headless');
        {{ end }}
        LOAD PROXYSQL SERVERS TO RUNTIME;
        SAVE PROXYSQL SERVERS TO DISK;

        LOAD MYSQL QUERY RULES TO RUNTIME;
        LOAD MYSQL SERVERS TO RUNTIME;
        LOAD MYSQL USERS TO RUNTIME;

      "
      /bin/echo $CUR_CS > /tmp/cs.file
    fi

