apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proxysql.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "proxysql.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxysql.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod | default "10" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxysql
              containerPort: 6033
              protocol: TCP
            - name: controller
              containerPort: 6032
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: {{ include "proxysql.fullname" . }}-data
              mountPath: /var/lib/proxysql
            - name: {{ include "proxysql.fullname" . }}-config
              mountPath: /etc/proxysql.cnf
              subPath: proxysql.cnf
            - name: {{ include "proxysql.fullname" . }}-config
              mountPath: /tmp/hg-scheduler.bash
              subPath: hg-scheduler.bash
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "proxysql.fullname" . }}-config
          configMap:
            name: {{ include "proxysql.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: {{ include "proxysql.fullname" . }}-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi
