apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "proxysql.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "proxysql.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxysql.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod | default "300" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxysql
              containerPort: 6033
              protocol: TCP
            - name: controller
              containerPort: 6032
              protocol: TCP
          livenessProbe:
            exec:
              command: ["/usr/local/sbin/liveness.sh"]
          readinessProbe:
            exec:
              command: ["/usr/local/sbin/readiness.sh"]
          lifecycle:
            preStop:
              exec:
                command: ["/usr/local/sbin/drain.sh"]
          volumeMounts:
            - name: {{ include "proxysql.fullname" . }}-data
              mountPath: /var/lib/proxysql
            - name: {{ include "proxysql.fullname" . }}-config
              mountPath: /etc/proxysql.cnf
              subPath: proxysql.cnf
            - name: {{ include "proxysql.fullname" . }}-config
              mountPath: /usr/local/sbin/config-watcher.sh
              subPath: config-watcher.sh
            - name: {{ include "proxysql.fullname" . }}-config
              mountPath: /usr/local/sbin/liveness.sh
              subPath: liveness.sh              
            - name: {{ include "proxysql.fullname" . }}-config
              mountPath: /usr/local/sbin/readiness.sh
              subPath: readiness.sh              
            - name: {{ include "proxysql.fullname" . }}-config
              mountPath: /usr/local/sbin/drain.sh
              subPath: drain.sh              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "proxysql.fullname" . }}-config
          configMap:
            name: {{ include "proxysql.fullname" . }}-config
            defaultMode: 0555
  {{- if not .Values.proxysql.storage.persistent }}
        - name: {{ include "proxysql.fullname" . }}-data
          emptyDir: {}
  {{ else }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "proxysql.fullname" . }}-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi
  {{ end -}}
